import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { FaTwitter } from "react-icons/fa";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next.js Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-screen flex flex-col items-start justify-start p-24 bg-gradient-to-br from-white to-gray-200">
        <h1 className="text-2xl pb-16">ZKR</h1>
        <div className="flex flex-col items-start justify-start gap-y-12">
          <p className="text-5xl leading-normal">
            Focus on your vision <br />
            We handle the rest
          </p>
          <p className="w-[32rem] text-black/80 leading-8">
            We are passionate about leveraging technology to empower businesses
            and drive their success. With our comprehensive range of services,
            we aim to provide tailored solutions that address the unique
            challenges and goals of our clients.
          </p>
          <div className="flex flex-row items-center justify-start underline">
            <FaTwitter className="mr-2" />
            @zkrlabsllc
          </div>
          <div className="w-full gap-x-32 flex flex-row items-start justify-center overflow-hidden">
            <Image
              src="/assets/honeyjar.png"
              width={82}
              height={82}
              alt="honeyjar"
            />
            <Image
              src="/assets/honeyjar.png"
              width={82}
              height={82}
              alt="honeyjar"
            />
            <Image
              src="/assets/honeyjar.png"
              width={82}
              height={82}
              alt="honeyjar"
            />
            <Image
              src="/assets/honeyjar.png"
              width={82}
              height={82}
              alt="honeyjar"
            />
            <Image
              src="/assets/honeyjar.png"
              width={82}
              height={82}
              alt="honeyjar"
            />
            <Image
              src="/assets/honeyjar.png"
              width={82}
              height={82}
              alt="honeyjar"
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
